// <auto-generated />
namespace ProjectsboardsTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bruk2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bruk2));
        
        string IMigrationMetadata.Id
        {
            get { return "202112080820486_bruk2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
